services:
  - type: web
    name: worldweb-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -u bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: YOUR_TELEGRAM
        value: Worlds_Web
      - key: YOUR_PHONE
        value: +375333525727
      - key: YOUR_EMAIL
        value: info@worldweb.by
      - key: YOUR_WEBSITE
        value: https://worldweb.by
    plan: free