services:
  - type: worker
    name: worldweb-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -u bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: YOUR_TELEGRAM
        sync: false
      - key: YOUR_PHONE
        sync: false
      - key: YOUR_EMAIL
        sync: false
      - key: YOUR_WEBSITE
        sync: false
    plan: free
